[package]
name = "game-v3"
version = "0.0.1"
edition = "2024.alpha"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "ds/framework-2024", override = true }
pokemon = { local = "../pokemon" }

[addresses]
game = "0x0"
